apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: login:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app: login
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3001
      targetPort: 3001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: login
